language: go
go:
- 1.14.x
env:
  global:
  - GO111MODULE=on
  - secure: "TYgY/z00lbJfKSK68ys4UdpSdkZGCjtMnnPLTwQLyJvmZCWyicEd0LM1KIlRHcbMRazPzsyht0o3CFynn0JIsmyfPGmcFeppw2BzEDkofe1GdXX3kICGdfQTt9zViJsU+xxf6al2u0dId+tvVhlwZbDOMMAzw1XjIXqg8kumE/fAcciSI/4CuSG3lbezC9qoVPbUX3dzw+8sYdawvpa2x2PmbtDV+Xqh4TS3dIUxqoMj46ZuciwoC0i8FzTLyyJVkLEdzcY0elljTY92Vx5v8FAfiTZ5dAUE9zuIsAlHA0q00yOxKzUM7fvMRX65XbncJzZUzmbLgVZd4kLrXAXjjW/mA6mbJktSeV5P4f5rDISw8gUGUSn0yUJhuoUWTwkj8bRHjGstnWvy618GcNRiZ30s0IY4+dWdoWzeVY9k4KNdooFkCKqBJ9brt+saOSr2lhhHDXNkKfmZ4dKbrZDbIR7+VsKzm4nhyOo6qPhw2GUtZTdZRVcSS23vG/liwlSAGB2XSAkdZurzIHWu9zCZI3JI9ZYXWwM2QOKuS1Qg7bJ/Sl1YoEyRb0zMhH7BAQSpjUOdA9WaRMbL50PfpBOuKOg15jhjMgHD/Vb7LJqrc1X/j5kJvJB55aWzHmn5xaaRqJEFkDQrp1UIr7991BzjbG3Kvcevv92we+y1y/nGQq4="
script: make check
deploy:
  - provider: script
    skip_cleanup: false
    script: curl -sL https://git.io/goreleaser | bash
    on:
      tags: true
      condition: "$TRAVIS_OS_NAME = linux"
