version: "3.3"

services:
  sftp-basic:
    container_name: sftp-basic
    hostname: sftp-basic
    image: atmoz/sftp
    ports:
      - "2220:22"
    command: foo:password:::upload1,upload2
  sftp-key:
    container_name: sftp-key
    hostname: sftp-key
    image: atmoz/sftp
    ports:
      - "2221:22"
    command: foo::::upload1,upload2
    volumes:
      - "$PWD/ssh/key_without_passphrase.pub:/home/foo/.ssh/keys/key_without_passphrase.pub"
      - "$PWD/ssh/key_with_passphrase.pub:/home/foo/.ssh/keys/key_with_passphrase.pub"
  sftp-basic-and-key:
    container_name: sftp-basic-and-key
    hostname: sftp-basic-and-key
    image: atmoz/sftp
    ports:
      - "2222:22"
    command: foo:password:::upload1,upload2
    volumes:
      - "$PWD/ssh/key_without_passphrase.pub:/home/foo/.ssh/keys/key_without_passphrase.pub"
      - "$PWD/ssh/key_with_passphrase.pub:/home/foo/.ssh/keys/key_with_passphrase.pub"
      - "$PWD/ssh/sshd_config:/etc/ssh/sshd_config"
  sftp-basic-exporter:
    container_name: sftp-basic-exporter
    hostname: sftp-basic-exporter
    build:
      context: ../
      dockerfile: ./Dockerfile
    ports:
      - "8080:8080"
    environment:
      BIND_ADDRESS: 0.0.0.0
      LOG_LEVEL: debug
      SFTP_HOST: sftp-basic
      SFTP_PORT: 22
      SFTP_USER: foo
      SFTP_PASS: password
      SFTP_PATHS: "/upload1 /upload2"
  prometheus:
    container_name: prometheus
    hostname: prometheus
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - "$PWD/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml"
  grafana:
    container_name: grafana
    hostname: grafana
    image: grafana/grafana
    ports:
      - "3000:3000"
